[package]
name = "kvbench"
version = "0.1.0"
edition = "2021"
publish = false

[lints.clippy]
nursery = "deny"
pedantic = "deny"
style = "deny"
cargo = "deny"
option-if-let-else =  { level = "allow", priority = 1 }
#multiple-crate-versions = { level = "allow", priority = 1 }
missing-errors-doc = { level = "allow", priority = 1 }
cast-precision-loss = { level = "allow", priority = 1 }

[profile.release-nativecpu]
inherits = "release"
debug = true
# still unstable: https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-rustflags-option
# this is defined for make run_native
#rustflags = ["-C", "target-cpu=native"]

[dependencies]
clap = { version = "4", features = ["derive"] }
crossbeam-skiplist = "0"
go-parse-duration = "0"
nix = { version = "0", features = ["signal"] }
rand = { version = "0", features = ["small_rng"] }
# we are not using the async API and it pulls in a lot of dependencies
redis = { version = "0", default-features = false } 
strum = { version = "0", features = ["derive"] }
