[package]
name = "kvbench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.9"
go-parse-duration = "0.1.1"
rand = "0.8.5"
rand_xoshiro = "0.6.0"
